#!/bin/sh

# 受け取った標準出力
string=$(cat - )

# 引数
arguments="$1"


# 引数が"-a"の場合は真,なければ偽
echo "$1" | grep -w "\-a" && 
	
	# 真の場合,末尾に改行を付けずに出力
	echo $string | xargs busybox httpd -d || 

	# 偽の場合,末尾に改行を付け出力
	echo $string | xargs busybox httpd -d | awk '{print $0}'

