#!/bin/sh -eux

barcode -b $(cat $1 | 

	# awkで区切り文字をカンマに指定
	awk -F"," '{

		# 改行を" -b "に置換
		ORS = " -b "

		# 1フィールド目を出力
		print $1

	}' | 
	
	# sedで末尾の" -b "を改行に置換
	sed "s/ \-b \$/\n/"

	) -t 3x6+20+60 -o $2 && convert $2 $3
