#!/bin/sh -eu

# 変数input_fileに第1引数を代入
input_file=${1}
option_args=${2}

# input_fileを加工,変数に代入
output_file=$(

	echo "${input_file}" | 

	awk -F"/" '{

		# 拡張子".c"を".out"に置換
		sub( ".c$" , ".out")

		# "/tmp/"と変換後のファイル名を出力
		print "/tmp/"$NF

	}'

)

# 引数のファイルと実行バイナリの出力先を指定
gcc "${input_file}" -o "${output_file}" "${option_args}"

