#!/bin/sh

# ====== 環境変数の設定 ======
# ロケールの設定
export LC_ALL=C
export LANG=C

# GNU coreutilsの挙動をPOSIXに準拠
export POSIXLY_CORRECT=1
# ====== 環境変数の設定ここまで ======


# 変数"input_file"に第1引数を代入
input_file=${1}

# 変数"option_args"に第2引数を代入
option_args=${2}

# "input_file"からファイル名のみを抽出
output_file=$(basename "${input_file}")

# 変数展開でファイル名から拡張子を削除,"/tmp/"を行頭に,拡張子を".out"で出力
output_file="/tmp/${output_file%.c}.out"

# "option_args"があれば真,なければ偽
if [ -n "${option_args}" ] ; then

	# 真の場合は"option_args"を引数に追加
	gcc "${input_file}" -o "${output_file}" "${option_args}"

else

	# 偽の場合は引数のファイルと実行バイナリの出力先を指定
	gcc "${input_file}" -o "${output_file}"

fi

