#!/bin/sh

# 標準入力の有無を確認,あれば真,無ければ偽
if [ -p /dev/stdin ] ; then

	# 真の場合は標準入力を変数に代入
	input_string=$(cat - )

    echo "${input_string}" |

	# 行頭のタブ文字,"#",スペース,"- "を削除
	sed -e "s/^\t*//g" -e "s/^\#\+//g" -e "s/^ \+//g" -e "s/^- //g" |

	# 文字数をカウント
	wc -m

# 偽の場合は引数の数を確認,0以外で真,それ以外で偽
elif [ "${#}" != 0 ] ; then

	# 真の場合は引数のファイルの中身を変数に代入
	input_string=$(cat "${*}")

    echo "${input_string}" |

	# 行頭のタブ文字,"#",スペース,"- "を削除
	sed -e "s/^\t*//g" -e "s/^\#\+//g" -e "s/^ \+//g" -e "s/^- //g" |

	# 文字数をカウント
	wc -m
	
else

	# 偽の場合はメッセージを標準エラー出力に表示
	echo "please stdin or argment!" 1>&2

fi

