#!/bin/sh

# TMUXの起動を確認,あれば真,なければ偽
if [ -n "${TMUX}" ] ; then

	# 真の場合はメッセージを標準エラー出力に表示
	echo "tmux is started!" 1>&2
	
	# 空白行の挿入
	echo "" 1>&2

	# 既存のセッションの一覧を表示
	tmux ls

else

	# ホームディレクトリに戻る
	cd 

	# 偽の場合は既存のセッションにアタッチ
	tmux a ||

	# メッセージを標準エラー出力に表示
	echo "make session" 1>&2

	# セッションにアタッチできなかった場合は新規セッションを作成,即デタッチ
	tmux new-session -d -s edit
	tmux new-session -d -s git 
	tmux new-session -d -s httpd
	tmux new-session -d -s mpd 
	tmux new-session -d -s ssh 
	tmux new-session -d -s command 
	tmux new-session -d ;

	# グループ化し並列に処理
	{ 

		# 作成したセッションのペインを分割
		tmux split-window -v -t git &
		tmux split-window -v -t httpd &
		tmux split-window -v -t mpd &
		tmux split-window -v -t ssh ;

	}

	# 最初に作成したセッションにアタッチ
	tmux a -t edit

fi
