#!/bin/sh

# TMUXの起動を確認,あれば真,なければ偽
if [ -n "${TMUX}" ] ; then

	# 真の場合はメッセージを標準エラー出力に表示
	echo "tmux is started!" 1>&2

else

	# 偽の場合は既存のセッションにアタッチ
	tmux a ;

	# セッションにアタッチできなかった場合は新規セッションを作成
	# メッセージを標準エラー出力に表示
	echo "make session" 1>&2

	# それぞれセッションを作成し即デタッチ
	tmux new-session -d -s edit
	tmux new-session -d -s git
	tmux new-session -d -s httpd
	tmux new-session -d -s mpd
	tmux new-session -d -s ssh
	tmux new-session -d -s command
	tmux new-session -d
	tmux new-session -d

	# 最初に作成したセッションにアタッチ
	tmux a -t edit

fi

